comic.settings:
  type: config_object
  label: 'Comic module settings'
  mapping:
    id_comic:
      type: integer
      label: 'Id del comic'
    description_comic:
      type: text
      label: 'Descripción del comic'